### ISSUE TITLE
gitcount

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#307]
@jGaboardi do we need the gitcount notebook here? I am not sure when it is called.

I don't want to use it to generate an automatic changelog if that won't cause trouble. It is IMHO too noisy and I prefer to keep only user-facing changes in the changelog.

**Comment by jGaboardi** [comment]
It is called during the release action (e.g. [here](https://github.com/pysal/libpysal/blob/master/.github/workflows/release_and_publish.yml#L39) for `libpysal`). If `momepy` will not be running an automated `CHANGELOG` then  you are correct, there is no reason to have a `gitcount.ipynb`. (Is this correct, @sjsrey?)

**Comment by martinfleis** [comment]
The release action we have here assumes an updated changelog before you make a tag.

**Comment by sjsrey** [comment]
I think the automatic change log is causing more problems than it solves. 

 It might be better to use the git count to get some summary statistics, and then use those in a handcrafted change log.

**Comment by jGaboardi** [comment]
> I think the automatic change log is causing more problems than it solves.
> 
> It might be better to use the git count to get some summary statistics, and then use those in a handcrafted change log.

Probably a good idea, as the original intent (IIRC) was to make sure that all contributors received credit.

**Comment by martinfleis** [comment]
I guess that this resolves a lot of related issues - https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/

**Comment by jGaboardi** [comment]
Interesting...

**Comment by jGaboardi** [comment]
@martinfleis I am going to close this for now. Please re-open if we feel it's still something we need to address.
