### ISSUE TITLE
QST: mm.Blocks emits CRS mismatch warnings

### ISSUE THREAD

**Issue by cdkang** [pysal/momepy#321]
I deeply appreciate your sharing momepy. 

Now I test your code but face mm.Blocks error that says " I should use pd.concat". 

Further, I have another issue as below. 

```py
C:\anaconda\envs\geo\lib\site-packages\momepy\elements.py:631: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: PROJCS["Tokyo_Transverse_Mercator",GEOGCS["Tokyo", ...
Right CRS: PROJCS["Tokyo_Transverse_Mercator",GEOGCS["Tokyo", ...

  cut = gpd.overlay(
```
I have three dataframe such as building, streets, and tessellation.  

Thus, I need your advice on how to apply pd.concat or other ways to make Block file and match crs among files.

**Comment by martinfleis** [comment]
What you see is just a warning that your GeoDataFrames are not in the same CRS. From the snippet, it looks they are, it may be just a minor detail in WKT that is used for comparison here.

If you are sure that your data are in the same projection, you can ignore this issue. Alternatively, you can reproject all to the same CRS as:

```py
streets = streets.to_crs(buildings.crs)
tessellation = tessellation.to_crs(buildings.crs)
```

**Comment by cdkang** [comment]
Thank you for your information. Let me try.
