### ISSUE TITLE
QST: how to save graph to Shapefile?

### ISSUE THREAD

**Issue by cdkang** [pysal/momepy#323]
Hello, 

I want to save graph results such as closeness and betweenness to shape files. 

Please let me know how to do them.

**Comment by martinfleis** [comment]
Hi,

to save graph to shapefile, you need to convert it to GeoDataFrames following this guide http://docs.momepy.org/en/stable/user_guide/graph/convert.html and then you can save those GeoDataFrames.

```py
nodes, edges = momepy.nx_to_gdf(graph)
nodes.to_file("nodes.shp")
edges.to_file("edges.shp")
```

Does it resolve your issue?

**Comment by cdkang** [comment]
Thank you for your support. Let me try.
