### ISSUE TITLE
QST: input data type for momepy 

### ISSUE THREAD

**Issue by cdkang** [pysal/momepy#325]
Hello, 

I am wondering if I use my own shape files for momepy work. Or, should I use other types such as gpkg or geojson?

Also, should I preprocess my own shape files to remove overlapped parts in buildings and streets or other additional preprocessing work such as close gap and extend lines? In some cases of my shape files, I can not get global closeness  but can get local closeness. 

I want to know which type is the better for faster and stable analysis.

**Comment by martinfleis** [comment]
> I am wondering if I use my own shape files for momepy work. Or, should I use other types such as gpkg or geojson?

It doesn't matter which file format you use as input. All of them are converted to `geopandas.GeoDataFrame` when you read them.

> should I preprocess my own shape files to remove overlapped parts in buildings and streets or other additional preprocessing work such as close gap and extend lines?

Well, that depends on your use case. In some cases, overlapping parts cause issues, in other they do not. Closing gaps and extending lines is the same, you need to know if your data needs it and for what purpose. There's no one approach that fits all cases.

We can talk about issues with specific data and specific functions.

> In some cases of my shape files, I can not get global closeness but can get local closeness.

What do you mean by "I can not get global closeness"? It errors, it takes a long time (it does) or what?

> I want to know which type is the better for faster and stable analysis.

A clean dataset is always better as it causes fewer issues. But it shouldn't make a difference in performance.

**Comment by cdkang** [comment]
Thank you so much.
