### ISSUE TITLE
Summary at the custom-zone level

### ISSUE THREAD

**Issue by CWen001** [pysal/momepy#327]
Thank you very much for this package, and it solves many calculating problems for us who are urban planners but from non-technical backgrounds.

`momepy` currently provides tools to compute morphological index at the building, tessellation, and street level. It indeed considers the concept of block when constructing one using `momepy.Blocks()` to integrate the data of buildings, street, and tesselations.  However, the morphological index at the block level (or generally zones covering several tesselations or even cut across them) is not yet the central focus.

My question, maybe a request for best practices or functionality, is how can we summarize the index from the current three levels to a custom zoning?  For example, after we calculate some indexes at the city level, then we may want to summarize them according to its different districts. 

So far, my plan is to use the spatial join tool to add the district information back to buildings, streets, and tesselations within them, and then do some `df.groupby('district_id').agg(...)` considering mean or weighted mean. But it has potential problems when dealing with cross-boundary entities.

**Comment by CWen001** [comment]
Hi,

Thank you very much for your reply, and It solves my problems. Closing the issue.

Another question, in the long term, is `memopy` going to extend the metrics to the block level? For example, Number of Road Intersection (RIQ), Road Intersection Separation Distance (RISD), Fractal Dimension at the block level (FDB).

**Comment by martinfleis** [comment]
> Another question, in the long term, is memopy going to extend the metrics to the block level? For example, Number of Road Intersection (RIQ), Road Intersection Separation Distance (RISD), Fractal Dimension at the block level (FDB).

I am happy to add those. Can you open an issue describing them? To know how are they supposed to be measured. Ideally with some reference to where it comes from.
