### ISSUE TITLE
BUG?: angular betweenness is returning strange results

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#346]
### Describe the problem

Angular betweenness is apparently not correct. I think. Instead of giving us smooth result, it often returns step-like fragments. I don't know what is causing it but it is present in most of cases so it is something we are doing wrong. Somewhere. It will require a bit of debugging and finding an alternative implementation to compare to (that may be tricky).

![Screenshot 2022-03-15 at 10 06 04](https://user-images.githubusercontent.com/36797143/158354502-8a2cac37-db8d-4811-8f7d-c967ead1bfe2.png)
 

### Steps to reproduce

This is visible even in our user guide, so you can reproduce it using that. http://docs.momepy.org/en/stable/user_guide/graph/centrality.html#Angular-betweenness

### Versions of your packages

latest

**Comment by songololo** [comment]
@martinfleis let me know if you want to try a test via `cityseer`, I'd be happy to take a look at bridging the workflows.

**Comment by songololo** [comment]
@martinfleis yes, let's do an experiment, I'm happy to write the bridging workflow then we can see if it works.

**Comment by martinfleis** [comment]
@songololo see #347 that includes data (and a fix of this bug). Check that but I think that it may be better to move this discussion into a separate issue discussing interface between momepy and cityseer and how can we use it here.
