### ISSUE TITLE
hi res logo?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#354]
@martinfleis Do we have interest in a higher resolution logo? The current logo is great, but it might benefit a *bit* with a higher dpi image.

**Comment by martinfleis** [comment]
We have a vector version here https://github.com/pysal/momepy/blob/main/docs/_static/logo.svg. If you think some raster versions need a higher DPI, go for it.

**Comment by jGaboardi** [comment]
Can you share the code you used for creating the logo?

**Comment by martinfleis** [comment]
I seriously doubt I have it anywhere :D. It is a random part of some tessellation with splot's `plot_spatial_weights` heavily edited by hand in illustrator.

**Comment by jGaboardi** [comment]
OK. I will take a look and see about replicating faithfully. High likelihood of failure. LOL

**Comment by martinfleis** [comment]
@jGaboardi what is the issue with the SVG that you want to replicate it?

**Comment by jGaboardi** [comment]
I meant that I might try to recreate the current logo with some small improvements. The main purpose would be be to archive some code to reproducible easily if you want to make adjustments in the future. If you think we don't want/need it then we can probably close this issue.

**Comment by martinfleis** [comment]
That is a different discussion I think. 

If you think that logo somewhere in the docs or readme should be if a higher resolution as suggested in the first post, we can easily export a high dpi version from that SVG.

If you think that the logo needs a refresh and reproducibility, I am not going to stop you playing with that but I wouldn't spend time myself doing that.

**Comment by jGaboardi** [comment]
I'll go ahead and close this for now. Potentially reopen in the future.
