### ISSUE TITLE
CI: issue with parallelism?

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#367]
@jGaboardi we seem to have an issue with the parallelism of pytest - https://github.com/pysal/momepy/runs/7122626097?check_suite_focus=true. It had happened a couple of times before and rerunning the test fixes the issue but it is annoying. Do you know how to avoid it?

**Comment by jGaboardi** [comment]
Yeah, maybe using `pytest-xdist` in the CI setting where we're only allowed 2 cores is causing more trouble than it's worth. Locally, using `pytest-xdist` is a boon (especially when using a beefy VM with a ton of cores), but probably could stick with single core for CI. I'll make a PR to remove.
