### ISSUE TITLE
limit numpy version evaluations in diversity.Percentiles

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#390]
https://github.com/pysal/momepy/blob/67d9509c5e6a7122998e175dc47606f61f242c97/momepy/diversity.py#L901-L917

Yesterday I put the `numpy` version declaration within the for loop (line 908-911). This probably makes more sense to do it once before the food loop + declare the keyword in line 901.

xref #387

**Comment by jGaboardi** [comment]
We get ≈.1 second improvement by moving the version call outside the for loop. For reference, a single column `Percentile()` instance – `meshedness` – from cell 48 in the [sdss2022 notebook](https://github.com/martinfleis/sdss22-workshop/blob/main/demo-notebook.ipynb):
* version check inside loop
  *  2.71 s ± 48.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
* version check outside loop
  * 2.8 s ± 169 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by martinfleis** [comment]
Let's move it outside at least as a good coding practice.
