### ISSUE TITLE
add a project.toml?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#415]
Should we add a `project.toml` file to complement our current `setup.py` and [`setup.cfg`](https://github.com/pysal/momepy/blob/main/setup.cfg)?

https://github.com/pysal/momepy/blob/e836a503c8b58d6309fc74bd2b143c5e284fb55b/setup.py#L1

**Comment by martinfleis** [comment]
I honestly lost track on what is good practice here. `setup.py`, `setup.cfg`, `pyproject.toml` are a bit overlapping imho. So the only point of reference for me are PRs in geopandas (https://github.com/geopandas/geopandas/pull/2419, https://github.com/geopandas/geopandas/pull/2512, https://github.com/geopandas/geopandas/pull/2424) so I'd ideally try to use the same model. I'll leave this decision to you as you seem to know more.
