### ISSUE TITLE
clean up references on docs site

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#424]
http://docs.momepy.org/en/stable/references.html#references

Specifics:
* **AF19** – remove colon in title
* **Fel18** – correct title; add DOI
  * Resilience and urban design: A systems approach to the study of resilience in urban form – Learning from the case of the Gorbals
  * 10.48730/yrsa-7747
* **GMBeiraoD12** – add journal link and paper link (no DOI?)
  * http://www.urbanform.org/online_public/2012_1.shtml
  * http://www.urbanform.org/online_unlimited/pdf2012/201216_27.pdf
* **HLM12** – remove redundant cities
* **HBP17** – add link to paper
  * https://pure.tudelft.nl/ws/portalfiles/portal/51462127/Paer_66_book_proceedings_28092017.pdf
* **McG95** – add author, add DOI, etc
  * info here - https://www.fs.usda.gov/treesearch/pubs/3064
* **TRBM20** – correct pages; add DOI
  * 48(8):2188-2205, doi: 10.1177/2399808320967680.

**Comment by martinfleis** [comment]
> GMBeiraoD12 – add journal link and paper link (no DOI?)

Yeah, Urban Morphology journal is stuck in the past and does not have DOIs.
