### ISSUE TITLE
need to keep requirements.txt?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#433]
Since we now list dependencies in [`pyproject.toml`](https://github.com/pysal/momepy/blob/804b93bd02984a7cde9a372de878bac56b31acd4/pyproject.toml#L41-L48), I am wondering if we need to keep the [`requirements.txt`](https://github.com/pysal/momepy/blob/main/requirements.txt) file?

**Comment by martinfleis** [comment]
for pip install maybe?

**Comment by jGaboardi** [comment]
OK, probably best to simply keep it for now. Especially since the `pyproject.toml`/`setup.cfg` stuff isn't fully worked out.
