### ISSUE TITLE
patch release pinning pandas=1.4.4?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#437]
xref https://github.com/pysal/momepy/pull/427#pullrequestreview-1127124471

> I am thinking we should do a patch release that changes our requirements to avoid ppl running into that bug...

@martinfleis Should we go ahead and pin [`pandas=1.4.4`](https://github.com/pandas-dev/pandas/releases/tag/v1.4.4) for a patch release until the actual fix in `pandas` is available?

**Comment by jGaboardi** [comment]
This can probably closed now that [`pandas==1.5.1`](https://pandas.pydata.org/pandas-docs/version/1.5.1/whatsnew/v1.5.1.html#fixed-regressions) is out, right?

**Comment by martinfleis** [comment]
yes. and it was already resolve https://github.com/pysal/momepy/pull/438

**Comment by jGaboardi** [comment]
LOL. Whoops.
