### ISSUE TITLE
roundabout_simplification not implemented=

### ISSUE THREAD

**Issue by gitfeldhase** [pysal/momepy#450]
Hello everyone,

I am tyring to use the roundabout_simplification function of momepy but I think it is not implemented yet for momepy being installed via pip.
I do not find the function in
`venv/lib/python3.8/site-packages/momepy/preprocessing.py`

Any chances it will be implemented soon?

Best regards

### Steps to reproduce

```gdf = mm.roundabout_simplification(gdf)```

doe not find the function, also the function is not in file mentioned above.

### Versions of your packages

```Name: momepy
Version: 0.5.4
Summary: Urban Morphology Measuring Toolkit
Home-page: http://momepy.org
Author: Martin Fleischmann
Author-email: martin@martinfleischmann.net
License: BSD
Location: /home/lars/venvs/geo_tools_dhn/lib/python3.8/site-packages
Requires: geopandas, libpysal, networkx, packaging, pygeos, tqdm
Required-by: 
```

**Comment by gregmaya** [comment]
Hi ! 
I believe you can still use the function if you download the latest (dev) version. 
[DOCs](https://docs.momepy.org/en/latest/user_guide/preprocessing/roundabout_simplification.html)
It might not be as stable as with functions that are part of the official release, but at least it will give you a glimpse of what to expect once is fully out.
Glad someone is using it! All feedback welcome
G

**Comment by martinfleis** [comment]
Main is as stable as the latest release, wouldn't worry about that. 

I'll have a look what needs to be done prior next release. There may be some PRs we want in before cutting 0.6.

**Comment by gitfeldhase** [comment]
Good to hear,
if it will be added with the next release I might consider using it until then with dev.

Looking forward for the release :)
