### ISSUE TITLE
momepy 0.6

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#460]
I'd like to get 0.6 out soon-ish so I can start working on #443 and #340/#406. Ideally, we have GSoC results in but I can't spend a lot of time myself finishing those PRs, so they may be left out.

What should be in:

- #396
- #377
- #448

+ a note, we need to change the GSoC policy for the next time and award "pass" only when a PR is merged or nearly merged.

I'd say that a deadline is end of Jan, probably around 28th to make it for the next meta.

**Comment by Monzyy** [comment]
When can we expect this to be released?

**Comment by martinfleis** [comment]
@Monzyy we wanted to finish the work on #396 and https://github.com/pysal/momepy/pull/377 but that may take some time. 

@jGaboardi thoughts on cutting main as 0.6.0?

**Comment by jGaboardi** [comment]
Any reason not to? Are you still trying to get #448 in to `v0.6.0`?

**Comment by martinfleis** [comment]
Ah yes, re-reading that it should be a simple note. Will open a PR and we can release afterwards.

**Comment by martinfleis** [comment]
https://github.com/pysal/momepy/actions/runs/4854183412/jobs/8651232875 whoops.

**Comment by jGaboardi** [comment]
So it's a problem with `pyproject.toml`?

**Comment by martinfleis** [comment]
It is out 🎉. Available on PyPI now and on conda-forge soon.
