### ISSUE TITLE
read_file: IllegalArgumentException: point array must contain 0 or >1 elements

### ISSUE THREAD

**Issue by IngJuanMaSuarez** [pysal/momepy#466]
### Describe the problem

Hi everyone.

When i try to read this [shapefile](https://drive.google.com/file/d/1GKbleAQ-pQVca_04VeweuJRdXtg5zPiU/view?usp=sharing), i getting this error:

```
File c:\Users\vpt\anaconda3\envs\geo_env\Lib\site-packages\geopandas\io\file.py:259, in _read_file(filename, bbox, mask, rows, engine, **kwargs)
    256     path_or_bytes = filename
    258 if engine == "fiona":
--> 259     return _read_file_fiona(
    260         path_or_bytes, from_bytes, bbox=bbox, mask=mask, rows=rows, **kwargs
    261     )
    262 elif engine == "pyogrio":
...
    121 else:
    122     return simple_geometries_1d(coords, indices, GeometryType.LINESTRING, out=out)

GEOSException: IllegalArgumentException: point array must contain 0 or >1 elements
```

I read this shapefile in a software GIS without problem. That file has reference system and i can to visualize in QGIS. But in GeoPandas i getting this error.

### Steps to reproduce

```
import geopandas as gpd

pluto_exploded = gpd.read_file(r"C:\Users\vpt\Desktop\zlvas\shapefiles\10.lot_line_type\mappluto_exploded_v2\mappluto_exploded_v2_proj.shp")
```

### Versions of your packages

```
geopandas = 0.12.2
geopandas-base = 0.12.2
```

### Your operating system

Windows 11 Home Single Language

**Comment by martinfleis** [comment]
This has nothing to do with `momepy`, you don't even import it in the snippet above, why have you reported here? We clearly cannot do anything about this.

I can confirm that geopandas does not open this, doesn't matter if through `fiona` or `pyogrio` engine, both fail, while QGIS doesn't seem to have an issue. I am not sure why though, probably some issue with the data Fiona and pyogrio don't expect.

It should be reported either to the [geopandas](https://github.com/geopandas/geopandas) repository or [Fiona](https://github.com/Toblerity/Fiona) and [pyogrio](https://github.com/geopandas/pyogrio). That is where the issue can be potentially fixed.
