### ISSUE TITLE
CI: `TestElements.test_get_node_id_ratio` failing in `311-dev.yaml`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#481]
[`TestElements.test_get_node_id_ratio`](https://github.com/pysal/momepy/actions/runs/4663297948/jobs/8254502100?pr=480#step:5:171) is failing in [`311-dev.yaml`](https://github.com/pysal/momepy/blob/main/ci/envs/311-dev.yaml):

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by martinfleis** [comment]
GeoPandas regression -> https://github.com/geopandas/geopandas/issues/2867

**Comment by jGaboardi** [comment]
Resolved by https://github.com/geopandas/geopandas/pull/2868. Nice fix, @martinfleis!
