### ISSUE TITLE
update copyright year

### ISSUE THREAD

**Issue by jGaboardi** [pysal/momepy#501]
xref https://github.com/pysal/pysal/issues/1282#issuecomment-1636779187

We need to update the copyright year in the `momepy` docs. Either:
* swap 2022 for 2023; or
* remove the ending year, as done in [`spaghetti`](https://github.com/pysal/spaghetti/blob/075bce14abe343ef548b86ea64e6edad2b4ae299/docs/conf.py#L55)

**Comment by martinfleis** [comment]
Can we just do `Copyright 2018-` so we don't have to update it every year? Or maybe drop it altogether? Is it needed for any purpose?

**Comment by jGaboardi** [comment]
Yes, that is the second bullet point option I listed.

**Comment by jGaboardi** [comment]
If we're good with that, I'll put in the PR.

**Comment by martinfleis** [comment]
fine with that
