### ISSUE TITLE
BUG: get_node_id does not support string IDs

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#519]
If `edge_id` column is using string IDs, this line will fail as numpy supports only numeric dtypes.

https://github.com/pysal/momepy/blob/78c1b244f3acef60d77cbce98e3426c755b3033d/momepy/elements.py#L807C16-L807C24

We need to change it to `pd.isna`.

**Comment by jGaboardi** [comment]
So this switch will only involve the condition check:

```python
if pd.isna(eid):
    results_list.append(np.nan)
```

Or also perhaps the appended value[^1]:

```python
if pd.isna(eid):
    results_list.append(pd.NA)
```

[^1]: now seeing this is [very experimental](https://pandas.pydata.org/docs/user_guide/missing_data.html#experimental-na-scalar-to-denote-missing-values)

**Comment by martinfleis** [comment]
Yes, the condition check needs to change. The null value is also a good point because we probably don't want a float `np.nan` in an array of strings. And technically, ID could be anything hashable. So `pd.NA` is not that bad idea.
