### ISSUE TITLE
Test user guide only on main?

### ISSUE THREAD

**Issue by martinfleis** [pysal/momepy#560]
Currently, we execute notebooks in the user guide to test them for failure on every CI run, including PRs. Do we want to keep doing it? It might be enough to run that only on main and in the nightly CI. @jGaboardi thoughts? I takes 11 minutes.

**Comment by jGaboardi** [comment]
Yes, let's do only main & nightli. And maybe even only 2 twice a week is enough?

**Comment by martinfleis** [comment]
Twice a week is the current "nightly" schedule already.

**Comment by jGaboardi** [comment]
> Twice a week is the current "nightly" schedule already.

Good point.
